# Generated by Django 5.1.5 on 2025-05-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeexpense',
            name='task_detail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
