# Generated by Django 5.1.5 on 2025-05-30 03:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_incomeexpense_task_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeexpense',
            name='date_upt',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
