# Generated by Django 5.1.5 on 2025-05-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_incomeexpense_date_upt'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeexpense',
            name='amount1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
