# Generated by Django 5.1.5 on 2025-05-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myfriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('emial', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='photo')),
                ('created', models.DateField()),
            ],
        ),
    ]
