# Generated by Django 5.1.5 on 2025-05-15 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_post_created_date_post_photo_alter_post_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('post_body', models.TextField()),
                ('photo1', models.ImageField(upload_to='bolgphoto')),
                ('photo2', models.ImageField(upload_to='bolgphoto')),
                ('photo3', models.ImageField(upload_to='bolgphoto')),
                ('created_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
